import turtle
import math
sun = turtle.Turtle()
sun.shape('circle')
sun.color('yellow')
mercury = turtle.Turtle()
mercury.shape('circle')
mercury.shapesize(0.18)
mercury.color('blue')
venus = turtle.Turtle()
venus.shape('circle')
venus.color('orange')
venus.shapesize(0.44)
earth = turtle.Turtle()
earth.shape('circle')
earth.color('blue')
earth.shapesize(0.46)
mars = turtle.Turtle()
mars.shape('circle')
mars.color('red')
mars.shapesize(0.24)
jupyter = turtle.Turtle()
jupyter.shape('circle')
jupyter.color('orange')
jupyter.shapesize(5.1)
titan = turtle.Turtle()
titan.shape('circle')
titan.color('orange')
titan.shapesize(4.3)
sun.shapesize(1)
mercury.up()
venus.up()
earth.up()
mars.up()
jupyter.up()
titan.up()
mercury.goto(39+8,0)
venus.goto(72+0.5,0)
earth.goto(100+1.7,0)
mars.goto(152+14,0)
jupyter.goto(520+25,0)
titan.goto(953+53,0)
mercury.down()
venus.down()
earth.down()
mars.down()
jupyter.down()
titan.down()
for theta in range(36000):
    mercury.goto(39*math.cos(math.radians(122.2*theta/50))+8,
                 math.sqrt(39**2-8**2)*math.sin(math.radians(122.2*theta/50)))
    venus.goto(72*math.cos(math.radians(47.8*theta/50))+0.5,
               math.sqrt(72**2-0.5**2)*math.sin(math.radians(47.8*theta/50)))
    earth.goto(100*math.cos(math.radians(29.5*theta/50))+1.7,
               math.sqrt(100**2-1.7**2)*math.sin(math.radians(29.5*theta/50)))
    mars.goto(152*math.cos(math.radians(15.7*theta/50))+14,
              math.sqrt(152**2-14**2)*math.sin(math.radians(15.7*theta/50)))
    jupyter.goto(520*math.cos(math.radians(2.48*theta/50))+25,
                 math.sqrt(520**2-25**2)*math.sin(math.radians(2.48*theta/50)))
    titan.goto(953*math.cos(math.radians(theta/50))+53,
               math.sqrt(953**2-53**2)*math.sin(math.radians(theta/50)))
